### ISSUE TITLE
Error when installing package

### ISSUE THREAD

**Issue by sillasgonzaga** [joelkuiper/personograph#1] opened 2015-09-15 00:26 UTC
So I tried to download your package but got this error

> install_github("joelkuiper/personograph")
> Downloading github repo joelkuiper/personograph@master
> Installing personograph
> Skipping 1 packages not available: Depends:
> grImport
> "C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
>   "C:/Users/Sillas/AppData/Local/Temp/Rtmpucd45f/devtools238c61187702/joelkuiper-personograph-238a1f8" --library="C:/Program  \
>   Files/R/R-3.2.2/library" --install-tests 

ERROR: dependency 'Depends' is not available for package 'personograph'
- removing 'C:/Program Files/R/R-3.2.2/library/personograph'
  Error: Command failed (1)

**Comment by joelkuiper** [comment] 2015-09-15 09:53
Hmm looks like a windows specific issue. I'll take a look if I can reproduce it here!

**Comment by joelkuiper** [comment] 2015-09-15 10:59
Was a mistake in the DESCRIPTION, weird that it wasn't an issue on Linux/Mac!
Should be fixed now, thanks for reporting.

**Closed as completed by joelkuiper** 2015-09-15 10:59 UTC
